test

diff --git a/.github/workflows/Process_create_release.yml b/.github/workflows/Process_create_release.yml
--- a/.github/workflows/Process_create_release.yml
+++ b/.github/workflows/Process_create_release.yml
@@ -56,23 +56,23 @@ jobs:
           echo "https://api.github.com/repos/${{ github.repository }}/releases/tags/$version"
           
           release=details=$(
-            curl -L \
+            curl -L -s --fail-with-body \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
               https://api.github.com/repos/${{ github.repository }}/releases/tags/$version
           )
           
-          # release_id=$(echo "$release_details" | jq .id)
-          # pre_release=$(echo "$release_details" | jq .prerelease)
+          release_id=$(echo "$release_details" | jq .id)
+          pre_release=$(echo "$release_details" | jq .prerelease)
 
-          # if [ "$pre_release" == "false" ]; then
-          #   echo "Can not modify Full Release"
-          #   echo "# ${{ env.failure_ico }} Can not modify Full Release ($version) ${{ env.failure_ico }}" >> $GITHUB_STEP_SUMMARY
-          #   exit 1
-          # fi
+          if [ "$pre_release" == "false" ]; then
+            echo "Can not modify Full Release"
+            echo "# ${{ env.failure_ico }} Can not modify Full Release ($version) ${{ env.failure_ico }}" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
 
-          # echo "release_id=$release_id" >> $GITHUB_OUTPUT
+          echo "release_id=$release_id" >> $GITHUB_OUTPUT
 
       - name: Create
         id: create
